import Head from "next/head";
import Cards from "@/components/Cards";
import NavBar from "@/components/NavBar";
import styles from "@/styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Neumaticos Norte</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="img/bridgestone.png" />
      </Head>
      <main className={styles.main}>
        <div className={styles.header}>
          <img className={styles.logo} src="img/logo.png"></img>
          <h1 className={styles.titulo}>Neumáticos Norte</h1>
        </div>
        <NavBar />
        <Cards />
      </main>
    </>
  );
}
